name: Deploy Django Backend

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r backend/requirements.txt

      - name: Run Migrations
        run: python backend/manage.py migrate

      - name: Deploy
        run: echo "Deploying Django Backend..."
