name: Deploy Django Backend

on: 
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade wheel
          pip install -r backend/requirements.txt

      - name: Wait for Database (PostgreSQL Example)
        run: |
          echo "Waiting for database to be ready..."
          until nc -z -v -w30 db 5432; do
            echo "Waiting for database..."
            sleep 5
          done
          echo "Database is up!"

      - name: Run Migrations
        run: python backend/manage.py migrate

      - name: Run Tests (Optional)
        run: python backend/manage.py test

      - name: Deploy
        run: echo "Deploying Django Backend..."
